apiVersion: v1
kind: Pod
metadata:
  name: valaxy-deployment
  labels:
    app: valaxy-devops-project
spec:
  containers:
    - name: valaxy-devops-project
      image: dileep95/spring:tagVersion
      imagePullPolicy: Always
      ports:
      - containerPort: 8050
